theme = "modern"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "net"
device = "enp7s0"
ip = true
speed_up = false
interval = 3

[[block]]
block = "net"
device = "wlp6s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
interval = 3

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 1
